/** \file
 *  This C header file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : Generator.g
 *     -                            On : 2024-10-10 19:38:51
 *     -                 for the lexer : GeneratorLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer 
GeneratorLexer

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pGeneratorLexer, which is returned from a call to GeneratorLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 *
 * The methods in pGeneratorLexer are  as follows:
 *
 *  - 
 void
      pGeneratorLexer->T__13(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__14(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__15(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__16(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__17(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__18(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__19(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__20(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__21(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__22(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__23(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__24(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__25(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__26(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__27(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__28(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__29(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__30(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__31(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__32(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__33(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__34(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__35(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__36(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__37(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__38(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__39(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__40(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__41(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__42(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__43(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__44(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__45(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__46(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__47(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__48(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__49(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__50(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__51(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__52(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__53(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->T__54(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->Str(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->Char(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->Hex(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->Bits(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->Dec(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->DIGITS(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->Bool(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->Whitespace(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->Identifier(pGeneratorLexer)
 *  - 
 void
      pGeneratorLexer->Tokens(pGeneratorLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_GeneratorLexer_H
#define _GeneratorLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct GeneratorLexer_Ctx_struct GeneratorLexer, * pGeneratorLexer;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for 
GeneratorLexer

 */
struct GeneratorLexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;

     void
     (*mT__13)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__14)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__15)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__16)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__17)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__18)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__19)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__20)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__21)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__22)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__23)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__24)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__25)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__26)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__27)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__28)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__29)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__30)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__31)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__32)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__33)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__34)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__35)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__36)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__37)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__38)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__39)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__40)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__41)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__42)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__43)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__44)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__45)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__46)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__47)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__48)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__49)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__50)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__51)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__52)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__53)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mT__54)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mStr)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mChar)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mHex)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mBits)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mDec)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mDIGITS)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mBool)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mWhitespace)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mIdentifier)	(struct GeneratorLexer_Ctx_struct * ctx);

     void
     (*mTokens)	(struct GeneratorLexer_Ctx_struct * ctx);
    const char * (*getGrammarFileName)();
    void            (*reset)  (struct GeneratorLexer_Ctx_struct * ctx);
    void	    (*free)   (struct GeneratorLexer_Ctx_struct * ctx);
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pGeneratorLexer GeneratorLexerNew         (
pANTLR3_INPUT_STREAM
 instream);
ANTLR3_API pGeneratorLexer GeneratorLexerNewSSD      (
pANTLR3_INPUT_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
lexer
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define T__13      13
#define T__14      14
#define T__15      15
#define T__16      16
#define T__17      17
#define T__18      18
#define T__19      19
#define T__20      20
#define T__21      21
#define T__22      22
#define T__23      23
#define T__24      24
#define T__25      25
#define T__26      26
#define T__27      27
#define T__28      28
#define T__29      29
#define T__30      30
#define T__31      31
#define T__32      32
#define T__33      33
#define T__34      34
#define T__35      35
#define T__36      36
#define T__37      37
#define T__38      38
#define T__39      39
#define T__40      40
#define T__41      41
#define T__42      42
#define T__43      43
#define T__44      44
#define T__45      45
#define T__46      46
#define T__47      47
#define T__48      48
#define T__49      49
#define T__50      50
#define T__51      51
#define T__52      52
#define T__53      53
#define T__54      54
#define Bits      4
#define Bool      5
#define Char      6
#define DIGITS      7
#define Dec      8
#define Hex      9
#define Identifier      10
#define Str      11
#define Whitespace      12
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for GeneratorLexer
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
