/** \file
 *  This C header file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : Generator.g
 *     -                            On : 2024-10-10 19:38:50
 *     -                for the parser : GeneratorParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The parser 
GeneratorParser

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pGeneratorParser, which is returned from a call to GeneratorParserNew().
 *
 * The methods in pGeneratorParser are  as follows:
 *
 *  - 
 GeneratorParser_source_return
      pGeneratorParser->source(pGeneratorParser)
 *  - 
 GeneratorParser_typeRef_return
      pGeneratorParser->typeRef(pGeneratorParser)
 *  - 
 GeneratorParser_funcSignature_return
      pGeneratorParser->funcSignature(pGeneratorParser)
 *  - 
 GeneratorParser_sourceItem_return
      pGeneratorParser->sourceItem(pGeneratorParser)
 *  - 
 GeneratorParser_statement_return
      pGeneratorParser->statement(pGeneratorParser)
 *  - 
 GeneratorParser_block_statment_return
      pGeneratorParser->block_statment(pGeneratorParser)
 *  - 
 GeneratorParser_if_statement_return
      pGeneratorParser->if_statement(pGeneratorParser)
 *  - 
 GeneratorParser_while_statement_return
      pGeneratorParser->while_statement(pGeneratorParser)
 *  - 
 GeneratorParser_repeat_statement_return
      pGeneratorParser->repeat_statement(pGeneratorParser)
 *  - 
 GeneratorParser_break_statement_return
      pGeneratorParser->break_statement(pGeneratorParser)
 *  - 
 GeneratorParser_expr_statement_return
      pGeneratorParser->expr_statement(pGeneratorParser)
 *  - 
 GeneratorParser_expr_return
      pGeneratorParser->expr(pGeneratorParser)
 *  - 
 GeneratorParser_assignment_expr_return
      pGeneratorParser->assignment_expr(pGeneratorParser)
 *  - 
 GeneratorParser_logical_expr_return
      pGeneratorParser->logical_expr(pGeneratorParser)
 *  - 
 GeneratorParser_comparison_expr_return
      pGeneratorParser->comparison_expr(pGeneratorParser)
 *  - 
 GeneratorParser_additive_expr_return
      pGeneratorParser->additive_expr(pGeneratorParser)
 *  - 
 GeneratorParser_multiplicative_expr_return
      pGeneratorParser->multiplicative_expr(pGeneratorParser)
 *  - 
 GeneratorParser_unary_expr_return
      pGeneratorParser->unary_expr(pGeneratorParser)
 *  - 
 GeneratorParser_primary_expr_return
      pGeneratorParser->primary_expr(pGeneratorParser)
 *  - 
 GeneratorParser_braces_return
      pGeneratorParser->braces(pGeneratorParser)
 *  - 
 GeneratorParser_place_return
      pGeneratorParser->place(pGeneratorParser)
 *  - 
 GeneratorParser_literal_return
      pGeneratorParser->literal(pGeneratorParser)
 *  - 
 GeneratorParser_un_op_return
      pGeneratorParser->un_op(pGeneratorParser)
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 * 
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_GeneratorParser_H
#define _GeneratorParser_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct GeneratorParser_Ctx_struct GeneratorParser, * pGeneratorParser;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/* ========================
 * BACKTRACKING IS ENABLED
 * ========================
 */

typedef struct GeneratorParser_source_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GeneratorParser_source_return;



typedef struct GeneratorParser_typeRef_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GeneratorParser_typeRef_return;



typedef struct GeneratorParser_funcSignature_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GeneratorParser_funcSignature_return;



typedef struct GeneratorParser_sourceItem_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GeneratorParser_sourceItem_return;



typedef struct GeneratorParser_statement_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GeneratorParser_statement_return;



typedef struct GeneratorParser_block_statment_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GeneratorParser_block_statment_return;



typedef struct GeneratorParser_if_statement_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GeneratorParser_if_statement_return;



typedef struct GeneratorParser_while_statement_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GeneratorParser_while_statement_return;



typedef struct GeneratorParser_repeat_statement_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GeneratorParser_repeat_statement_return;



typedef struct GeneratorParser_break_statement_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GeneratorParser_break_statement_return;



typedef struct GeneratorParser_expr_statement_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GeneratorParser_expr_statement_return;



typedef struct GeneratorParser_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GeneratorParser_expr_return;



typedef struct GeneratorParser_assignment_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GeneratorParser_assignment_expr_return;



typedef struct GeneratorParser_logical_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GeneratorParser_logical_expr_return;



typedef struct GeneratorParser_comparison_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GeneratorParser_comparison_expr_return;



typedef struct GeneratorParser_additive_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GeneratorParser_additive_expr_return;



typedef struct GeneratorParser_multiplicative_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GeneratorParser_multiplicative_expr_return;



typedef struct GeneratorParser_unary_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GeneratorParser_unary_expr_return;



typedef struct GeneratorParser_primary_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GeneratorParser_primary_expr_return;



typedef struct GeneratorParser_braces_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GeneratorParser_braces_return;



typedef struct GeneratorParser_place_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GeneratorParser_place_return;



typedef struct GeneratorParser_literal_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GeneratorParser_literal_return;



typedef struct GeneratorParser_un_op_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;

}
    GeneratorParser_un_op_return;




/** Context tracking structure for 
GeneratorParser

 */
struct GeneratorParser_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_PARSER   pParser;

     GeneratorParser_source_return
     (*source)	(struct GeneratorParser_Ctx_struct * ctx);

     GeneratorParser_typeRef_return
     (*typeRef)	(struct GeneratorParser_Ctx_struct * ctx);

     GeneratorParser_funcSignature_return
     (*funcSignature)	(struct GeneratorParser_Ctx_struct * ctx);

     GeneratorParser_sourceItem_return
     (*sourceItem)	(struct GeneratorParser_Ctx_struct * ctx);

     GeneratorParser_statement_return
     (*statement)	(struct GeneratorParser_Ctx_struct * ctx);

     GeneratorParser_block_statment_return
     (*block_statment)	(struct GeneratorParser_Ctx_struct * ctx);

     GeneratorParser_if_statement_return
     (*if_statement)	(struct GeneratorParser_Ctx_struct * ctx);

     GeneratorParser_while_statement_return
     (*while_statement)	(struct GeneratorParser_Ctx_struct * ctx);

     GeneratorParser_repeat_statement_return
     (*repeat_statement)	(struct GeneratorParser_Ctx_struct * ctx);

     GeneratorParser_break_statement_return
     (*break_statement)	(struct GeneratorParser_Ctx_struct * ctx);

     GeneratorParser_expr_statement_return
     (*expr_statement)	(struct GeneratorParser_Ctx_struct * ctx);

     GeneratorParser_expr_return
     (*expr)	(struct GeneratorParser_Ctx_struct * ctx);

     GeneratorParser_assignment_expr_return
     (*assignment_expr)	(struct GeneratorParser_Ctx_struct * ctx);

     GeneratorParser_logical_expr_return
     (*logical_expr)	(struct GeneratorParser_Ctx_struct * ctx);

     GeneratorParser_comparison_expr_return
     (*comparison_expr)	(struct GeneratorParser_Ctx_struct * ctx);

     GeneratorParser_additive_expr_return
     (*additive_expr)	(struct GeneratorParser_Ctx_struct * ctx);

     GeneratorParser_multiplicative_expr_return
     (*multiplicative_expr)	(struct GeneratorParser_Ctx_struct * ctx);

     GeneratorParser_unary_expr_return
     (*unary_expr)	(struct GeneratorParser_Ctx_struct * ctx);

     GeneratorParser_primary_expr_return
     (*primary_expr)	(struct GeneratorParser_Ctx_struct * ctx);

     GeneratorParser_braces_return
     (*braces)	(struct GeneratorParser_Ctx_struct * ctx);

     GeneratorParser_place_return
     (*place)	(struct GeneratorParser_Ctx_struct * ctx);

     GeneratorParser_literal_return
     (*literal)	(struct GeneratorParser_Ctx_struct * ctx);

     GeneratorParser_un_op_return
     (*un_op)	(struct GeneratorParser_Ctx_struct * ctx);

     ANTLR3_BOOLEAN
     (*synpred14_Generator)	(struct GeneratorParser_Ctx_struct * ctx);

     ANTLR3_BOOLEAN
     (*synpred15_Generator)	(struct GeneratorParser_Ctx_struct * ctx);

     ANTLR3_BOOLEAN
     (*synpred16_Generator)	(struct GeneratorParser_Ctx_struct * ctx);

     ANTLR3_BOOLEAN
     (*synpred17_Generator)	(struct GeneratorParser_Ctx_struct * ctx);

     ANTLR3_BOOLEAN
     (*synpred18_Generator)	(struct GeneratorParser_Ctx_struct * ctx);

     ANTLR3_BOOLEAN
     (*synpred23_Generator)	(struct GeneratorParser_Ctx_struct * ctx);

     ANTLR3_BOOLEAN
     (*synpred31_Generator)	(struct GeneratorParser_Ctx_struct * ctx);

     ANTLR3_BOOLEAN
     (*synpred33_Generator)	(struct GeneratorParser_Ctx_struct * ctx);

     ANTLR3_BOOLEAN
     (*synpred41_Generator)	(struct GeneratorParser_Ctx_struct * ctx);

     ANTLR3_BOOLEAN
     (*synpred49_Generator)	(struct GeneratorParser_Ctx_struct * ctx);

     ANTLR3_BOOLEAN
     (*synpred50_Generator)	(struct GeneratorParser_Ctx_struct * ctx);
    // Delegated rules

    const char * (*getGrammarFileName)();
    void            (*reset)  (struct GeneratorParser_Ctx_struct * ctx);
    void	    (*free)   (struct GeneratorParser_Ctx_struct * ctx);
/* @headerFile.members() */
pANTLR3_BASE_TREE_ADAPTOR	adaptor;
pANTLR3_VECTOR_FACTORY		vectors;
/* End @headerFile.members() */
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pGeneratorParser GeneratorParserNew         (
pANTLR3_COMMON_TOKEN_STREAM
 instream);
ANTLR3_API pGeneratorParser GeneratorParserNewSSD      (
pANTLR3_COMMON_TOKEN_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
parser
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define T__13      13
#define T__14      14
#define T__15      15
#define T__16      16
#define T__17      17
#define T__18      18
#define T__19      19
#define T__20      20
#define T__21      21
#define T__22      22
#define T__23      23
#define T__24      24
#define T__25      25
#define T__26      26
#define T__27      27
#define T__28      28
#define T__29      29
#define T__30      30
#define T__31      31
#define T__32      32
#define T__33      33
#define T__34      34
#define T__35      35
#define T__36      36
#define T__37      37
#define T__38      38
#define T__39      39
#define T__40      40
#define T__41      41
#define T__42      42
#define T__43      43
#define T__44      44
#define T__45      45
#define T__46      46
#define T__47      47
#define T__48      48
#define T__49      49
#define T__50      50
#define T__51      51
#define T__52      52
#define T__53      53
#define T__54      54
#define Bits      4
#define Bool      5
#define Char      6
#define DIGITS      7
#define Dec      8
#define Hex      9
#define Identifier      10
#define Str      11
#define Whitespace      12
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for GeneratorParser
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
