/** \file
 *  This C header file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : MyLanguage.g
 *     -                            On : 2024-11-23 15:18:34
 *     -                 for the lexer : MyLanguageLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer 
MyLanguageLexer

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pMyLanguageLexer, which is returned from a call to MyLanguageLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 *
 * The methods in pMyLanguageLexer are  as follows:
 *
 *  - 
 void
      pMyLanguageLexer->T__40(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__41(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__42(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__43(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__44(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__45(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__46(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__47(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__48(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__49(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__50(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__51(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__52(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__53(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__54(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__55(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__56(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__57(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__58(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__59(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__60(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__61(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__62(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__63(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__64(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__65(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__66(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__67(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__68(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__69(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__70(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__71(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__72(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__73(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__74(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__75(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__76(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__77(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->T__78(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->BuiltInType(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->Str(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->Char(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->Hex(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->Bits(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->Dec(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->DIGITS(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->Bool(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->WS(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->SINGLE_COMMENT(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->MULTI_COMMENT(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->Identifier(pMyLanguageLexer)
 *  - 
 void
      pMyLanguageLexer->Tokens(pMyLanguageLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_MyLanguageLexer_H
#define _MyLanguageLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct MyLanguageLexer_Ctx_struct MyLanguageLexer, * pMyLanguageLexer;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for 
MyLanguageLexer

 */
struct MyLanguageLexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;

     void
     (*mT__40)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__41)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__42)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__43)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__44)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__45)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__46)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__47)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__48)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__49)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__50)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__51)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__52)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__53)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__54)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__55)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__56)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__57)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__58)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__59)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__60)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__61)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__62)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__63)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__64)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__65)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__66)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__67)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__68)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__69)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__70)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__71)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__72)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__73)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__74)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__75)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__76)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__77)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mT__78)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mBuiltInType)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mStr)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mChar)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mHex)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mBits)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mDec)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mDIGITS)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mBool)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mWS)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mSINGLE_COMMENT)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mMULTI_COMMENT)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mIdentifier)	(struct MyLanguageLexer_Ctx_struct * ctx);

     void
     (*mTokens)	(struct MyLanguageLexer_Ctx_struct * ctx);
    const char * (*getGrammarFileName)();
    void            (*reset)  (struct MyLanguageLexer_Ctx_struct * ctx);
    void	    (*free)   (struct MyLanguageLexer_Ctx_struct * ctx);
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pMyLanguageLexer MyLanguageLexerNew         (
pANTLR3_INPUT_STREAM
 instream);
ANTLR3_API pMyLanguageLexer MyLanguageLexerNewSSD      (
pANTLR3_INPUT_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
lexer
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define T__40      40
#define T__41      41
#define T__42      42
#define T__43      43
#define T__44      44
#define T__45      45
#define T__46      46
#define T__47      47
#define T__48      48
#define T__49      49
#define T__50      50
#define T__51      51
#define T__52      52
#define T__53      53
#define T__54      54
#define T__55      55
#define T__56      56
#define T__57      57
#define T__58      58
#define T__59      59
#define T__60      60
#define T__61      61
#define T__62      62
#define T__63      63
#define T__64      64
#define T__65      65
#define T__66      66
#define T__67      67
#define T__68      68
#define T__69      69
#define T__70      70
#define T__71      71
#define T__72      72
#define T__73      73
#define T__74      74
#define T__75      75
#define T__76      76
#define T__77      77
#define T__78      78
#define Args      4
#define Array      5
#define ArrayAccess      6
#define ArrayType      7
#define Bits      8
#define BlockStatement      9
#define Body      10
#define Bool      11
#define BreakStatement      12
#define BuiltInType      13
#define Char      14
#define Condition      15
#define DIGITS      16
#define Dec      17
#define Else      18
#define ExpressionStatement      19
#define FuncSignature      20
#define Function      21
#define FunctionCall      22
#define Hex      23
#define Identifier      24
#define IfStatement      25
#define Index      26
#define MULTI_COMMENT      27
#define Parameter      28
#define ParameterList      29
#define RepeatCondition      30
#define SINGLE_COMMENT      31
#define Slice      32
#define Source      33
#define Statement      34
#define Str      35
#define Then      36
#define TypeRef      37
#define WS      38
#define WhileStatement      39
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for MyLanguageLexer
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
